apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: kydq2022/udagram-api-user:latest
        ports:
        - containerPort: 8080
        env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: project3-configs
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: project3-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project3-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project3-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: project3-secret
                  key: JWT_SECRET
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: project3-configs
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: project3-configs
                  key: AWS_REGION